Add className to spinner component
LaunchPadLab/lp-components pull request #493
Opened 2021-10-18 15:37 UTC by ghrlee

quick change to the Spinner component to use the className "spinner" in place of id

## Author Checklist

- [x] Add unit test(s)
- [ ] Update version in package.json (see the [versioning guidelines](https://github.com/LaunchPadLab/opex-public/blob/master/gists/npm-package-guidelines.md#pull-requests-and-deployments))
- [x] Update documentation (if necessary)
- [ ] Add story to storybook (if necessary)
- [x] Assign dev reviewer

2021-10-18 19:43 UTC, chawes13 commented on src/indicators/spinner.js
> +  return <div className="spinner" { ...filterInvalidDOMProps(props) } />
I think we should allow for the user to also specify an additional classname. We can do this using the `classnames` package. You can reference an example of this in `src/forms/buttons/button-area.js`.

2021-10-19 18:00 UTC, chawes13 commented on migration-guides/v6.0.0.md
> +1. The tag on `<Spinner />` now uses the classname `spinner` in place of an id
`className` is a JSX specific prop, so I think you can just use "class" here!

2021-10-19 18:01 UTC, chawes13 commented on migration-guides/v6.0.0.md
> +#### 6. The tag on `<Spinner />` now uses the classname `spinner` in place of an id
Can you merge in the latest from v6 into your branch? 6, 7, and 8 were recently added

2021-10-19 18:02 UTC, chawes13 commented on migration-guides/v6.0.0.md
> +<div className={classnames('spinner', props.className)} />
This guide is focused on the change that a developer has to make to their existing code, not the actual code change that was made. The breaking change here is the styling change. If a dev updated their project to use this version of `lp-components`, the actually spinner animation wouldn't show up until they modified their scss files (i.e., replacing any reference of `#spinner` with `.spinner`)

2021-11-01 13:22 UTC, chawes13 commented on migration-guides/v6.0.0.md
> +1. The tag on `<Spinner />` now uses the class `spinner` in place of an id which can be custom
"...which can be custom" implies to me that the spinner class can be overridden. Our implementation allows for appending _additional_ classes, but not customizing the base class. Would you mind updating this language?

2021-11-02 20:35 UTC, chawes13 commented on migration-guides/v6.0.0.md
> +`<Spinner />` utilizes a classname and can accept additional custom classes in order to accomodate views where more than one spinners are necessary.
Typo: `accommodate`

2021-11-02 20:35 UTC, chawes13 commented on migration-guides/v6.0.0.md
> +//
Were you going to add a comment here?

2021-11-02 20:38 UTC, chawes13 reviewed
Looking really good!! Just a few finishing touches and we'll be ready to merge 🤩

2021-11-02 20:38 UTC, chawes13 commented on src/indicators/spinner.js
> +  className: PropTypes.string
When a prop isn't required, it's best to declare your intent with a default prop. For this use case, an empty string would suffice.

2021-11-15 21:55 UTC, ghrlee commented
@chawes13 sorry for the huge delay

2021-11-15 22:45 UTC, chawes13 requested changes
So close! Just a few finishing touches

2021-11-15 22:45 UTC, chawes13 commented on migration-guides/v6.0.0.md
> +  text-align: center;
It'd be great if you chose another declaration here to really showcase the benefit of customizing just a specific spinner. When I read this example, you're not changing anything from above so it reads a little confusing to me. E.g., 
```css
.custom-spinner {
  margin-bottom: 10px;
}

2021-11-15 22:45 UTC, chawes13 commented on migration-guides/v6.0.0.md
> +// After
I don't think you need this here, since you have it on line 208

2021-11-15 22:45 UTC, chawes13 commented on src/indicators/spinner.js
> +  className: ''
This isn't accurate. In `propTypes` you use `PropTypes` to declare the type of the prop. In `defaultProps`, you declare the default value for the properties that aren't required in `propTypes`

2021-11-15 22:45 UTC, chawes13 commented on src/indicators/spinner.js
> +  className: ''
Here's an example: https://github.com/LaunchPadLab/lp-components/blob/ead699069fa1a2c322c7a117b3c2c6a196c2b1c1/src/forms/inputs/input.js#L37-L45

2021-11-15 22:45 UTC, chawes13 commented on test/indicators/spinner.test.js
> +  expect(wrapper.find('div.custom').exists()).toBe(true)
Can you also assert that the `.spinner` class is present as well?

2022-01-11 14:43 UTC, chawes13 requested changes

2022-01-11 14:43 UTC, chawes13 commented on src/indicators/spinner.js
> +  className: 'spinner'
If `className` isn't provided, your div will look like this:
```jsx
<div class="spinner spinner">
```
An empty string would be a more appropriate default (ignored by `classnames` util)

2022-01-11 14:43 UTC, chawes13 commented on migration-guides/v6.0.0.md
> +}
I think there might have been a miscommunication. I did not intend for you to also delete the code with `.spinner`. I think you need to show both.

2022-01-11 20:57 UTC, chawes13 approved these changes
🚀 nice!

2022-01-11 20:57 UTC, merged