update sortable table story to fix CustomHeader sorting
LaunchPadLab/lp-components pull request #500
Opened 2021-11-03 15:20 UTC by aojin

The associated fix to Storybook SortableTable for CustomHeader. We were not passing down the onClick handler.

2021-11-03 15:47 UTC, chawes13 requested changes
Few minor comments in-line. Can you bump the version and remove all the .DS_Store documents? I'll create a separate issue to make sure those are added to `.gitignore` in the future

2021-11-03 15:47 UTC, chawes13 commented on src/tables/table-column.js
> + * @param {Function} [headerComponent] - A custom header component for the column. Will be passed the configuration of the column, as well as the current `sortPath` / `ascending` and an `onClick` han
To be consistent, can you wrap "onClick" in single backticks?

2021-11-03 15:47 UTC, chawes13 commented on src/tables/table-column.js
> + *
I think we should have all examples _after_ the params have all been declared

2021-11-03 18:25 UTC, chawes13 commented
@aojin Looks good, just needs a version bump! This change can be made in `package.json`.

2021-11-09 20:22 UTC, chawes13 commented
@aojin Code looks good -- needs a version bump to pass versionator's check

2021-11-09 20:23 UTC, chawes13 requested changes
Version in `package.json`

2021-11-10 19:59 UTC, aojin commented
Sorry for the delay! Version bumped to 5.4.2!

2021-11-11 13:18 UTC, chawes13 approved these changes
🚀

2021-11-11 13:18 UTC, merged