Update link to NPM package guidelines in readme
LaunchPadLab/lp-components pull request #512
Opened 2021-11-19 21:27 UTC by rgaban

- Issues #[508](https://github.com/LaunchPadLab/lp-components/issues/508): NPM package guidelines link has moved 
- Updated link to npm package guidelines link in readme
- 
## Author Checklist

- [ ] Add unit test(s)
- [ ] Update version in package.json (see the [versioning guidelines](https://github.com/LaunchPadLab/opex-public/blob/master/gists/npm-package-guidelines.md#pull-requests-and-deployments))
- [x] Update documentation (if necessary)
- [ ] Add story to storybook (if necessary)
- [x] Assign dev reviewer

2021-11-22 20:37 UTC, chawes13 reviewed
Thank you! Can you bump the version in `package.json` as a patch release?

https://semver.org/#summary

2021-11-30 20:42 UTC, chawes13 commented
@rgaban I have exciting news! We were able to change the default branch to `main`, so the appropriate link is now: https://github.com/LaunchPadLab/opex-public/blob/main/gists/npm-package-guidelines.md

2021-12-03 15:05 UTC, chawes13 requested changes
Can you bump the version and swap out `master` for `main`? 🙏

2021-12-06 08:12 UTC, rgaban commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] Update version in package.json (see the [versioning guidelines](https://github.com/LaunchPadLab/opex-public/blob/main/gists/npm-package-guidelines.md#pull-requests-and-deployments))
@chawes13 found that the pull request request template needed to be updated as well!

2021-12-06 12:53 UTC, chawes13 approved these changes
🎉

2021-12-06 12:53 UTC, merged